import streamline from "./Thumbnails/Streamline.png";
import streamlineDemo from "./Thumbnails/StreamlineDemo.png";
import MDR from "./Thumbnails/MorrisDeltaRealty.png";
import portfolio from "./Thumbnails/Portfolio.png";
import movieApp from "./Thumbnails/MovieApp.png";
import YTC from "./Thumbnails/YoutubeClone.png";
const FakeProjects = [
  {
    id: 1,
    name: "Streamline",
    thumbnail_Url: streamline,
    site: "",
    github: "",
  },
  {
    id: 2,
    name: "Streamline Demo",
    thumbnail_Url: streamlineDemo,
    site: "",
    github: "",
  },
  {
    id: 3,
    name: "Morris Delta Realty",
    thumbnail_Url: MDR,
    site: "",
    github: "",
  },
  {
    id: 4,
    name: "Portfolio v1",
    thumbnail_Url: portfolio,
    site: "",
    github: "",
  },
  {
    id: 5,
    name: "Movie Application",
    thumbnail_Url: movieApp,
    site: "",
    github: "",
  },
  {
    id: 6,
    name: "Youtube Clone",
    thumbnail_Url: YTC,
    site: "",
    github: "",
  },
];

const FakeTasks = [
  {
    complete: true,
    date: "2023-02-09",
    description: "Add Completed Task Column.",
    importance_level: 1,
    project_Id: 1,
    task: "Completed Task",
    timestamp: "",
  },
  {
    complete: true,
    date: "2023-01-03",
    description: "Plan out components for contact Page.",
    importance_level: 1,
    project_Id: 1,
    task: "Plan Contact Page",
    timestamp: "",
  },
  {
    complete: true,
    date: "2023-02-14",
    description: "Use Yahoo Weather API to display weekly forecasts.",
    importance_level: 2,
    project_Id: 1,
    task: "Create Weekly Forecast Module.",
    timestamp: "",
  },
  {
    complete: true,
    date: "2023-02-13",
    description: "Plan which API's i will use for Dashboard page.",
    importance_level: 2,
    project_Id: 1,
    task: "Plan out Dashboard API's",
    timestamp: "",
  },
  {
    complete: true,
    date: "2023-03-03",
    description: "Plan which API's i will use for Dashboard page.",
    importance_level: 1,
    project_Id: 1,
    task: "Plan out Dashboard API's",
    timestamp: "",
  },
  {
    complete: false,
    date: "2023-03-13",
    description: "Deploy application using vercecl.",
    importance_level: 1,
    project_Id: 1,
    task: "Deploy live application",
    timestamp: "",
  },
  {
    complete: true,
    date: "2023-02-09",
    description: "Plan format and design of component and what it will entail.",
    importance_level: 1,
    project_Id: 1,
    task: "Plan Projects Component",
    timestamp: "",
  },
  {
    complete: true,
    date: "2023-02-09",
    description: "Create Edit Task Functionality through the task list.",
    importance_level: 1,
    project_Id: 1,
    task: "Edit Task Functionality",
    timestamp: "",
  },
  {
    complete: true,
    date: "2023-02-14",
    description:
      "Add Responsive styling to weather card module, to reflect weather forecast.",
    importance_level: 2,
    project_Id: 1,
    task: "Responsive Styling for Weather Card",
    timestamp: "",
  },
  {
    complete: true,
    date: "2023-02-28",
    description: "Give headings to progress displays.",
    importance_level: 2,
    project_Id: 1,
    task: "Label progress module components",
    timestamp: "",
  },
  {
    complete: true,
    date: "2023-02-28",
    description:
      "Design other metrics to display in projects module component.",
    importance_level: 2,
    project_Id: 1,
    task: "Design Progress Module",
    timestamp: "",
  },
  {
    complete: true,
    date: "2023-02-13",
    description: "Add Feature to show completed date for tasks.",
    importance_level: 2,
    project_Id: 1,
    task: "Show Completed Date",
    timestamp: "",
  },
  {
    complete: true,
    date: "2023-02-09",
    description:
      "Create Collections on Firebase console to hold date for Fred's Links, Resources, Planning, Projects & Backlog.",
    importance_level: 1,
    project_Id: 1,
    task: "Create Collections on Google Firebase ",
    timestamp: "",
  },
  {
    complete: true,
    date: "2023-02-14",
    description: "Add Weather pngs for weather display on dashboard.",
    importance_level: 2,
    project_Id: 1,
    task: "Add Weather Icons",
    timestamp: "",
  },
  {
    complete: true,
    date: "2023-02-09",
    description: "Order Task by timestamp creation.",
    importance_level: 3,
    project_Id: 1,
    task: "Oder Tasks",
    timestamp: "",
  },
  {
    complete: true,
    date: "2023-03-03",
    description: "Set up local storage functionality.",
    importance_level: 1,
    project_Id: 2,
    task: "Refactor Streamline applicaiton to run with local storage.",
    timestamp: "",
  },
  {
    complete: true,
    date: "2023-02-14",
    description: "Find Weather API to request data from.",
    importance_level: 3,
    project_Id: 1,
    task: "Implement Weather API",
    timestamp: "",
  },
  {
    complete: true,
    date: "2023-02-14",
    description: "Use YahooWeather API to display data.",
    importance_level: 3,
    project_Id: 1,
    task: "Use Yahoo Weather API",
    timestamp: "",
  },
  {
    complete: true,
    date: "2023-02-14",
    description:
      "Refactor add task, edit task, delete task, and undo task functionality to work with demo storage.",
    importance_level: 1,
    project_Id: 2,
    task: "Refactor CRUD functionality",
    timestamp: "",
  },
  {
    complete: true,
    date: "2023-03-03",
    description: "Add Importance level to edit task form.",
    importance_level: 2,
    project_Id: 1,
    task: "Edit task form.",
    timestamp: "",
  },
  {
    complete: true,
    date: "2023-02-28",
    description: "Add Importance level to edit task form.",
    importance_level: 1,
    project_Id: 1,
    task: "Edit task form.",
    timestamp: "",
  },
  {
    complete: true,
    date: "2023-01-03",
    description: "Add Portfolio, LinkedIn, Github, & Resume Links.",
    importance_level: 2,
    project_Id: 1,
    task: "Add Contact info on Contact Page",
    timestamp: "",
  },
  {
    complete: true,
    date: "2023-02-09",
    description:
      "Plan format and design of Planner Component and what it will entail.",
    importance_level: 3,
    project_Id: 1,
    task: "Plan out Planning Component.",
    timestamp: "",
  },
  {
    complete: true,
    date: "2023-02-09",
    description: "Create Delete Task Functionality through the edit list.",
    importance_level: 1,
    project_Id: 1,
    task: "Delete Task Functionality",
    timestamp: "",
  },
  {
    complete: true,
    date: "2023-03-15",
    description:
      "Add Demo Info Alerts to components to explain to users, component purposes.",
    importance_level: 1,
    project_Id: 1,
    task: "Create Demo Info Alert",
    timestamp: "",
  },
];
const futureProjects = [
  {
    complete: false,
    date: "2023-03-011",
    description:
      "Utilize Docker to host a Youtube Clone application with Django Backend",
    importance_level: 0,
    project_Id: 1,
    task: "Use Docker to depoy past application with backend.",
    timestamp: "",
  },
  {
    complete: false,
    date: "2023-03-013",
    description:
      "Have ability to set task deadlines and sprint lengths for projects and tasks",
    importance_level: 0,
    project_Id: 1,
    task: "Design and build functionality for a planner page for Streamline application.",
    timestamp: "",
  },
  {
    complete: false,
    date: "2023-03-015",
    description:
      "Create mobile application to display informative information for a personal trainer.",
    importance_level: 0,
    project_Id: 1,
    task: "Create Personal Trainer modbile application using React Native.",
    timestamp: "",
  },
  {
    complete: false,
    date: "2023-03-16",
    description:
      "Build ability to switch bewteen light and dark mode within streamline application.",
    importance_level: 0,
    project_Id: 1,
    task: "Build Light/Dark Mode for Streamline Application",
    timestamp: "",
  },
  {
    complete: false,
    date: "2023-03-16",
    description:
      "Use Google firebase authentication service to integrate a user based system into the streamline app.",
    importance_level: 0,
    project_Id: 1,
    task: "Google firebase authentication for users for Streamline application.",
    timestamp: "",
  },
];

export default { FakeProjects, FakeTasks, futureProjects };
